apiVersion: v1
kind: Pod
metadata:
  labels:
    team: frontend
spec:
  containers:
  - name: jnlp
    image: hub.xueerqin.net/yunwei/jenkins-slave-alpine-maven:v7
    command:
    - jenkins-agent
    tty: true
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "volume-workspace"
      readOnly: false
    - mountPath: "/home/jenkins/deployment"
      name: "volume-deployment"
    - mountPath: "/var/run/docker.sock"
      name: "volume-0"
      readOnly: false
    - mountPath: "/usr/bin/docker"
      name: "volume-1"
      readOnly: false
    - mountPath: "/usr/bin/kubectl"
      name: "volume-2"
      readOnly: false
    #- mountPath: "/home/jenkins/.m2/repository"
    #  name: "volume-maven"
    #  readOnly: false
    workingDir: "/home/jenkins/agent"
  securityContext:
    runAsUser: 0
  volumes:
  - hostPath:
      path: "/data/jenkins-slave/java"
    name: "volume-workspace"
  - hostPath:
      path: "/data/jenkins-slave/k8s-deploy/java"
    name: "volume-deployment"
  - hostPath:
      path: "/var/run/docker.sock"
    name: "volume-0"
  - hostPath:
      path: "/usr/bin/docker"
    name: "volume-1"
  - hostPath:
      path: "/usr/local/bin/kubectl"
    name: "volume-2"
#  - hostPath:
#      path: "/data/jenkins-slave/maven"
#    name: "volume-maven"
  - emptyDir:
      medium: ""
    name: "workspace-volume"